name: Pruebas automáticas del grupo
on:
  push:
    branches:
      - main
      - '*' # Ejecuta en 'main' y cualquier otra rama
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Clonar el repositorio
        uses: actions/checkout@v3
      - name: Configurar Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
      - name: Instalar dependencias
        run: |
          pip install pytest
      - name: Ejecutar pruebas
        run: |
          pytest -v
